#server:
#  port: 8082
#spring:
#  profiles:
#    active: dev
#  data:
#    mongodb:
#      uri : mongodb+srv://Narendra:1234567890@cluster0.bnbn0m3.mongodb.net/?retryWrites=true&w=majority
#      database: WalletBanking
#jwt:
# secret-key: 614E645267556B58703273357638792F423F4528482B4D6251655368566D5971